# Generated by Django 4.0.1 on 2022-02-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playertype',
            options={'verbose_name': 'Player Type', 'verbose_name_plural': 'Player Types'},
        ),
    ]
